name: Deploy Nginx

on:
  push:
    paths:
      - 'nginx/nginx.conf'
    branches:
      - main

env:
  EC2_PUBLIC_IP: 3.64.252.72  
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}  
  DOCKERHUB_USERNAME: doramar97

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2
          
      - name: SSH to EC2 instance
        run: | 
          echo "$SSH_PRIVATE_KEY" > dor.pem
          chmod 400 dor.pem
          scp -o StrictHostKeyChecking=no -i dor.pem nginx/deploy.sh ubuntu@$EC2_PUBLIC_IP:~/nginx
          scp -o StrictHostKeyChecking=no -i dor.pem nginx/nginx.conf ubuntu@$EC2_PUBLIC_IP:~/nginx
          ssh -i dor.pem ubuntu@$EC2_PUBLIC_IP "bash ~/nginx/deploy.sh"
    